### ISSUE TITLE
Command 'cozy-light link-domain' not found

### ISSUE THREAD

**Issue by ghost** [cozy-labs/cozy-light-domains#1]
Hi,

I've added this plugin but cozy don't recognize the command 'cozy-light link-domain'.
I'm working on Ubuntu Desktop with vagrant using a Debian x32 box (to simulate a Rpi).
After I've installed cozy, I've choosen 'cozy-light install-distro website'.
Then I just would like to test the hello application 'cozy-light install cozy-labs/hello'.
I've checked with the following command 'cozy-light display-config' and I can see:

```
{
  "apps": {
    "hello": {
      "name": "hello",
      "displayName": "Hello",
      "version": "1.0.0",
      "description": "Hello World for Cozy Light",
      "type": "static"
    }
  },
  "plugins": {
    "cozy-light-html5-apps": {
      "name": "cozy-light-html5-apps",
      "displayName": "HTML5 support for Cozy Light",
      "version": "0.1.0",
      "description": "Allow to deploy apps only made of static files."
    },
    "cozy-light-domains": {
      "name": "cozy-light-domains",
      "displayName": "Domain",
      "version": "0.1.0",
      "description": "Handle redirections based on domain name"
    },
    "cozy-light-githooks": {
      "name": "cozy-light-githooks",
      "displayName": "Githook",
      "version": "0.1.0",
      "description": "Plugin to update your apps after a github commit."
    }
  }
}
```

When I start cozy-light this is what I get:

```
cozy-light start
info - Configuring plugin cozy-light-html5-apps...
Server configured for app hello
info - Plugin cozy-light-html5-apps configured.
info - Configuring plugin cozy-light-domains...
info - Plugin cozy-light-domains configured.
info - Configuring plugin cozy-light-githooks...
info - Plugin cozy-light-githooks configured.
info - Cozy Light server is listening on port 19104...
info - Skip application hello.
```

First, I can't established the connection on 127.0.0.1:19104 with my browser on Ubuntu. (Why?)
So, I've decided to use the link-domain command but this is not working too...
When I run the command 'cozy-light link-domain monsiteweb.fr cozy-labs/hello' this display the help.
I've also tried to enable the plugin again 'cozy-light enable cozy-light-domains' but nothing.

Could someone help me for that ?

**Comment by frankrousseau** [comment]
Hello @VinceCOT. Thank you for reporting that bug. I will make some tests and come back to you soon.

**Comment by frankrousseau** [comment]
I think it's related to a big bug added recently (https://github.com/cozy-labs/cozy-light/issues/75). I'm looking for a solution but it's not easy. It's due to the initialization process that should be improved.

About the fact you have nothing when you connect directly on your Cozy Light, it's because you didn't install the `cozy-labs/cozy-light-simple-dashboard` plugin.

**Comment by frankrousseau** [comment]
Problem should be solved. @VinceCOT Could you try again?

**Comment by ghost** [comment]
I just try again and it seems to work.
Thank you for solving that !

**Comment by frankrousseau** [comment]
Great!
